### PR TITLE
Fix percentage shown in console for geom cache filling

### PR DESCRIPTION
**Pull request by patrickbr**
* add raw mode for getLoadStatusPercent() which counts to 100%, for console output
* mention xxd requirement in README

### CODE REVIEW

**Comment by patrickbr** [comment]
Progress on stdout for loading the geometry cache ended at 95%, which was a bit confusing. I added a "raw" mode to the `getLoadStatusPercent()` method which gives to current progress from 0 to 100%.

**Review by Grandro — APPROVED** [review]
Looks good to me. I thought maybe there is a more descriptive name for the parameter `raw`, perhaps `total` with negated logic?

**Comment by patrickbr** [comment]
I changed this as proposed, could you look over it again?

**Review by Grandro — APPROVED** [review]
Thank you, I believe this adds a little more clarity

**Pull request merged**
